# Generated by Django 3.2 on 2023-03-22 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_alter_productreview_rating'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wished_product',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wished_product',
            field=models.ManyToManyField(related_name='wishlist_product', to='products.Product'),
        ),
    ]
