# Generated by Django 3.2 on 2023-02-23 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
