# Generated by Django 3.2 on 2023-02-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='body',
            field=models.TextField(default='', max_length=250),
        ),
    ]
